### ISSUE TITLE
why not release OG internal

### ISSUE THREAD

**Issue by yEsPaP** [ama6nen/INZERNAL#17]
quote:
This is not internal, the first internal ever made for growtopia, that was developed by atipls, me, and tero.
That is our private internal and will not be released or sold.

what so special does it have, for it to not be released?

**Comment by aternis** [comment]
you are autistic

**Comment by yEsPaP** [comment]
> you are autistic

i think repo owner might be, wasting his brain on growtopia :)

**Comment by ama6nen** [comment]
> quote:
> This is not internal, the first internal ever made for growtopia, that was developed by atipls, me, and tero.
> That is our private internal and will not be released or sold.
> 
> what so special does it have, for it to not be released?

1. It was not my project, but a project by me, @atipls, and tero. They would not want to publish it, and me neither really.
2. It has not been updated since 2.996
3. Updating it would be too much work
   * World editor/viewer and Item editor/viewer broken due to new engine
   * Over 60 signatures to update
   * Messy code that wasn't made for other people to understand
   * Has many features with no explanation, and not good for future development 
   * Dozen obsolete structures that break all functionality
4. It did indeed have things that I didn't want to make public like crashing subservers, resolving name + world (patched now), respawn exploit, etc as an example. Many features and exploits in it haven't been patched to this day, although most have been.
5. I'm coding this because I want to, and what I wanted to achieve with this one is completely different from the other one.


> > you are autistic
> 
> i think repo owner might be, wasting his brain on growtopia :)

Most of the time is spent coding and reversing, testing the stuff is just a small part of it.
And it (hopefully) is obvious that I don't only do GT related stuff
Doing something you enjoy is far from "wasting" anything either

Also, next time use [Discussions](https://github.com/ama6nen/INZERNAL/discussions)

**Comment by yEsPaP** [comment]
> > quote:
> > This is not internal, the first internal ever made for growtopia, that was developed by atipls, me, and tero.
> > That is our private internal and will not be released or sold.
> > what so special does it have, for it to not be released?
> 
> 1. It was not my project, but a project by me, @atipls, and tero. They would not want to publish it, and me neither really.
> 2. It has not been updated since 2.996
> 3. Updating it would be too much work
>    
>    * World editor/viewer and Item editor/viewer broken due to new engine
>    * Over 60 signatures to update
>    * Messy code that wasn't made for other people to understand
>    * Has many features with no explanation, and not good for future development
>    * Dozen obsolete structures that break all functionality
> 4. It did indeed have things that I didn't want to make public like crashing subservers, resolving name + world (patched now), respawn exploit, etc as an example. Many features and exploits in it haven't been patched to this day, although most have been.
> 5. I'm coding this because I want to, and what I wanted to achieve with this one is completely different from the other one.
> 
> > > you are autistic
> > 
> > 
> > i think repo owner might be, wasting his brain on growtopia :)
> 
> Most of the time is spent coding and reversing, testing the stuff is just a small part of it.
> And it (hopefully) is obvious that I don't only do GT related stuff
> Doing something you enjoy is far from "wasting" anything either
> 
> Also, next time use [Discussions](https://github.com/ama6nen/INZERNAL/discussions)

well hey, cheating is never good, but atleast its not a a FPS game like CS:GO. only real retards cheat there

**Comment by ama6nen** [comment]
> well hey, cheating is never good, but atleast its not a a FPS game like CS:GO. only real retards cheat there

I don't care about "being good" just doing what I want to, and now closing this as mentioned discussions already
